name: rhkr8521 CI/CD

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  # Spring Boot 애플리케이션을 빌드하여 도커허브에 푸시하는 과정
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: ./gradlew clean bootJar

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/food_cicd_action:latest .

    - name: docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/food_cicd_action:latest

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
    - name: Set Docker socket permissions
      run: sudo chmod 666 /var/run/docker.sock

    - name: docker pull
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/food_cicd_action:latest
      
    - name: Remove existing container
      run: docker rm -f food 2>/dev/null || true

    - name: docker run new container
      run: docker run --name food --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/food_cicd_action:latest

    - name: delete unused docker images
      run: docker image prune -f
